### ISSUE TITLE
error about import apollocaffe

### ISSUE THREAD

**Issue by carrierlxk** [Russell91/apollocaffe#45]
I have compiled the apollocaffe following the link:http://apollocaffe.com/ .
However when I tried to run simple.py, I got error messages as follows: 
Traceback (most recent call last):
  File "examples/apollocaffe/simple.py", line 4, in <module>
    import apollocaffe
ImportError: No module named apollocaffe

So, I add path of apollocaffe to simple.py and  run again:

File "examples/apollocaffe/simple.py", line 4, in <module>
    import apollocaffe
  File "/home/carrierlxk/apollocaffe/python/apollocaffe/__init__.py", line 1, in <module>
    from cpp._apollocaffe import Tensor, ApolloNet, CppConfig, make_numpy_data_param, Blob
  File "/home/carrierlxk/apollocaffe/python/apollocaffe/cpp/__init__.py", line 1, in <module>
    import _apollocaffe
ImportError: libcaffe.so: cannot open shared object file: No such file or directory

Here is my LD_LIBRARY_PATH and PYTHONPATH:
LD_LIBRARY_PATH:
/home/carrierlxk/down/enter/lib::/home/carrierlxk/apollocaffe/build/lib
PYTHONPATH:
/home/carrierlxk/caffe-master/python:/home/carrierlxk/apollocaffe/python
I have tried to solve issue as #10 ,however it did not work here.

**Comment by Russell91** [comment]
Please make sure /home/carrierlxk/apollocaffe/build/lib/libcaffe.so exists and that /home/carrierlxk/apollocaffe/build/lib is in your LD_LIBRARY_PATH. It should not be possible to see the error,

ImportError: libcaffe.so: cannot open shared object file: No such file or directory

**Comment by carrierlxk** [comment]
Hi Russell,  
libcaffe.so exists in /home/carrierlxk/apollocaffe/build/lib/ and also my LD_LIBRARY_PATH is:/home/carrierlxk/down/enter/lib:/home/carrierlxk/apollocaffe/build/lib 
However the error  still exists.
