### ISSUE TITLE
AttributeError: Layer Convolution has no keyword argument kernel_w=1

### ISSUE THREAD

**Issue by da03** [Russell91/apollocaffe#65]
Even cannot create a conv layer.

**Comment by da03** [comment]
Traceback (most recent call last):
  File "t.py", line 12, in <module>
    net.f(Convolution('conv', (1,1), 1, bottoms=['data']))
  File "/home/ubuntu/apollocaffe/python/apollocaffe/layers/caffe_layers.py", line 24, in __init__
    super(Convolution, self).__init__(self, name, kwargs)
  File "/home/ubuntu/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 6, in __init__
    self.parse(sublayer, name, kwargs)
  File "/home/ubuntu/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 57, in parse
    raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))
AttributeError: Layer Convolution has no keyword argument kernel_w=1

**Comment by nicodjimenez** [comment]
does: `net.f(layers.Convolution(name="conv", bottoms=["image"], kernel_dim=(1, 1), num_output=1))` work? 

There's also the raw protobuf string API which works albeit verbosely, for example:
```
self.net.f("""
      name: "conv_big"
      type: "Convolution"
      bottom: "slice_0"
      top: "conv_big"
      param { lr_mult: 1 decay_mult: 0 }
      param { lr_mult: 2 decay_mult: 0 }
      convolution_param {
        num_output: 400
        kernel_size: 5
        stride: 1
        pad: 2
        weight_filler {
          type: "gaussian"
          std: 0.01
        }
        bias_filler {
          type: "constant"
          value: 0
        }
      }""")

```

**Comment by da03** [comment]
The problem can be located here: https://github.com/Russell91/apollocaffe/blob/master/python/apollocaffe/layers/layer_helpers.py#L10. In my computer, `param_names` would be `[]`. I think that's either due to my protobuf version (2.5.0), or due to the fact that `dir` in python is primitive.

**Comment by da03** [comment]
OK found a workaround. In `python/apollocaffe/layers/layer_helpers.py#L10`, change to `param_names = [s.name for s in layer.DESCRIPTOR.fields if s.endswith('_param')]`. I think `dir` is more for interactive purposes rather than having a consistent behavior across platforms.

**Comment by Johnson-yue** [comment]
hi guys,  I had same error and How to modify  https://github.com/Russell91/apollocaffe/blob/master/python/apollocaffe/layers/layer_helpers.py#L10 this file???

I had changed this 
`
 #param_names = kwargs.get('param_names', [])
param_names = [s.name for s in layer.DESCRIPTOR.fields if s.name.endswith('_param')]
`
but new error out :1234: 
# NameError: global name 'layer' is not defined
