### ISSUE TITLE
Can't run char_model.py

### ISSUE THREAD

**Issue by CPantojaI** [Russell91/apollocaffe#67]
When I tried to run it, said:

```
Traceback (most recent call last):
  File "char_model.py", line 148, in <module>
    forward(net, sentence_batches)
  File "char_model.py", line 84, in forward
    bottoms=['word%d' % step], param_names=['wordvec_param']))
  File "/home/cpantoja/Programas/apollocaffe/python/apollocaffe/layers/caffe_layers.py", line 197, in __init__
    super(Wordvec, self).__init__(self, name, kwargs)
  File "/home/cpantoja/Programas/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 6, in __init__
    self.parse(sublayer, name, kwargs)
  File "/home/cpantoja/Programas/apollocaffe/python/apollocaffe/layers/layer_headers.py", line 57, in parse
    raise AttributeError('Layer %s has no keyword argument %s=%s' % (param_type, k, v))
AttributeError: Layer Wordvec has no keyword argument vocab_size=256
```

Sorry If it has a very stupid and obvios solution, and new at caffe and apollocaffe and still I'm trying to understand the most basic things.

**Comment by ShangxuanWu** [comment]
Same question here.

**Comment by slippy0** [comment]
#65 offers a workaround that worked for me.
